### ISSUE TITLE
Support download multiple files / wildcard

### ISSUE THREAD

**Issue by clarkd** [huserben/PublishReleaseArtifactsExtension#1]
Is it possible to download multiple files?

We publish multiple files called "manifest.json" and want to download them all.

**Comment by huserben** [comment]
Hi @clarkd 

hmm with the current version you could have them in their own directory, which then would create a zip file of the folder and you can download those individual zips then later on.

Or you move all manifests in one directory (and rename them...) and then you can download this as a zip and move it back at the according place.

I think other options are currently not supported, and I cannot think right away about another good way of solving it.

**Comment by clarkd** [comment]
> Or you move all manifests in one directory (and rename them...) and then you can download this as a zip and move it back at the according place

We did this in the end - closing, as that's a reasonable solution.
