### ISSUE TITLE
unexpected end of file when downloading an artifact

### ISSUE THREAD

**Issue by EbenZhang** [huserben/PublishReleaseArtifactsExtension#10]
I uploaded a folder (name: dev_package) and got the below error when downloading.
The task seems not able to download the log at all. But press the Download All Logs button from the web UI I can see the uploaded folder (zipped as expected)

```
 Will store logs in D:\a\r1\a\DownloadReleaseArtifactTask
2020-12-02T09:57:40.9659846Z Looking for Artifact with the name dev_package.zip
2020-12-02T09:57:40.9661365Z Matching Artifact will be copied to D:\a\r1\a\dev_package
2020-12-02T09:57:40.9662368Z No existing Logs found - will initiating download...
2020-12-02T09:57:40.9671514Z Will get logs for current Relese
2020-12-02T09:57:40.9672119Z Organization: https://dev.azure.com/XXX/
2020-12-02T09:57:40.9672662Z Team Project ID: XXXX
2020-12-02T09:57:40.9673094Z Release ID: 197
2020-12-02T09:57:43.6991367Z ##[debug]task result: Failed
2020-12-02T09:57:43.7044427Z ##[error]Unhandled: unexpected end of file
```

**Comment by huserben** [comment]
Hi @EbenZhang 

when you say you uploaded, you mean you used  the specific upload task right?

Did the download ever work correctly and just stopped working now or did it never work?

I've never seen this error so far, but it sounds like something might have failed either during upload or download.

**Comment by EbenZhang** [comment]
i uploaded using the task from this extension.
i suspect it is something to do with
- the number of log files
- the size of the logs
- uploading of multiple artifacts 
maybe you can try add many steps into the job and upload a slightly large file, and add more than one  artifacts

**Comment by huserben** [comment]
Tahnks for sharing this, I'll try to reproduce it in the coming days.
Could you share the amount/size of the files your uploading, so I can try to be as close as possible to that?

I will let you know once I figure something out.

**Comment by EbenZhang** [comment]
I uploaded a 3MB zip file.

**Comment by LiborSoumar** [comment]
Hi @huserben,
I am experiencing the same problem. Is there any progress on this issue?

**Comment by huserben** [comment]
Hi

sorry for the quiet for so long. Back in december I tried to reproduce the problem but couldn't.
Could you share some more details from your setup and some logs @LiborSoumar ?

For example:
- Are you running Azure DevOps or DevOps Server
- Are you using self hosted agents or the Microsoft Hosted Agents
- What OS are the build agents running
- How many artifacts are you trying to upload/download
- What's the size of those artifacts

That way we might find a pattern that will help reproducing the problem.

**Comment by LiborSoumar** [comment]
Hi @huserben,
The issue has disappeared after one day on its own so now I can't reproduce it, either. But to answer your questions:
- I use Azude DevOps.
- Upload Release Artifact is run on MS hosted machine (Microsoft Windows Server 2019), while Download Release Artifact is run on self hosted machine.
- I am uploading two artifacts, (pdf - 1.3 Mb, zip - 144 Mb). Both files seemed to be alright on MS hosted machine but got corrupted during download.

**Comment by huserben** [comment]
Thanks for the info.

So it seems that it randomly happens, which would draw me to the conclusion that it might not be related to the task itself but maybe to some infrastructure.
If you're using a self-hosted machine, is this behind some corporate firewall or proxy that potentially could interfer?

@EbenZhang is the issue still happening for you? If so, are you also using self-hosted agents to download where it fails?
