### ISSUE TITLE
Can we please allow wildcards for the artifacts?

### ISSUE THREAD

**Issue by loganwol** [huserben/PublishReleaseArtifactsExtension#11]
I have an executable that generates json files and the names of files can vary based on which code path is executed. I want to upload all the json files but the task keeps failing because the assumption is artifactPath is only a path without any wildcards. So something like $(System.DefaultWorkingDirectory)\*.json outputs an error.

**Comment by huserben** [comment]
Hi @loganwol 

Wildcards are not supported in the task, so this is somewhat expected.
You could however use the CopyFiles task which supports wildcards and copy all the files you want to publish into a new folder. Then you point to that folder for publishing.

Does this solve your problem?

**Comment by loganwol** [comment]
Hi @huserben, 

thanks for the response. That should be fine. Let's say I copied the files to a new location for the json files to be $(System.DefaultWorkingDirectory)\investigate\, would the syntax change be $(System.DefaultWorkingDirectory)\investigate?

**Comment by huserben** [comment]
Hi @loganwol 

yes exactly, that should upload the complete folder with everything that in it :-)
