### ISSUE TITLE
Queries Around This Extension Upload/Download

### ISSUE THREAD

**Issue by abhijeetkatigar** [huserben/PublishReleaseArtifactsExtension#19]
Hi Benj,

I hope you are doing good.

I have some queries around this extension. Actually I have created one release pipeline and in that pipeline I have used Power DevOps Tool Installer extension for solution import. So I wanted to download the release pipeline logs to my repository. 
Can you please help me how I can use this extensions to address my requirement? 

Looking for your support.

Thanks
Abhijeet

**Comment by huserben** [comment]
Hi @abhijeetkatigar 

The extension is meant (as a workaround) to publish artifacts during a phase of a Release Pipeline and make it available in a later phase. For this it's repurposing the built-in log functionality, by adding the artifacts (as zip) to the logs and automatically downloading & extracting it in the download task.

Is this a requirement you have? If yes you can just use the publish task to publish a file or folder in the first phase and the download task in the later phase(s) to fetch those artifacts again.

If it's not, could you please elaborate more on what exactly you want to do?
