### ISSUE TITLE
How do you access the artifact after publishing in Release pipeline?

### ISSUE THREAD

**Issue by tbeavers** [huserben/PublishReleaseArtifactsExtension#20]
Apparently I am missing something here because I have published an html file using the Publish Release Artifact task and the log file reflects that it seemed to work:

Uploading C:\agent4\_work\r1\a\Performance Reporting\HTMLReports\Dashboard.html to logs...
Finished uploading - task complete

But how do I actually access/review the artifact after it is published/uploaded?

**Comment by huserben** [comment]
Hi @tbeavers 

As the release pipelines do not really support artifacts this tasks is using the logs to "store" them. The main intention was to be able to upload something and download it in a later stage with the "Download Release Artifact" Task.

However if you want to upload an artifact and then manually download it, you should find it in the logs. I believe you can download all logs as zip and then you you should find it in the folder of the phase that was running the upload (sorry I can't give more details as I have not used the release pipelines in a while, so I don't know by heart :-)).

Does this help you?

**Comment by Intraligator** [comment]
Hello. What size of uploaded file can be stored in logs? and these logs means this:
![image](https://github.com/huserben/PublishReleaseArtifactsExtension/assets/106267300/af1d21ab-a7a0-423b-b127-e5fadaef2b72)
