### ISSUE TITLE
Retrieving uploaded files

### ISSUE THREAD

**Issue by mudesai** [huserben/PublishReleaseArtifactsExtension#35]
Hi there, I am using the 'Upload Release Artifact' step in my release pipeline. I want to download the uploaded file manually and not consume it through the download step in the release pipeline. I see that the logs say that the file was uploaded in logs. How can I access the file? Is it possible to do what I am asking?

**Comment by huserben** [comment]
Hi @mudesai 

yes, you can simply download the logs of your release and should have the artifacts in there:
![Download all logs](https://github.com/huserben/PublishReleaseArtifactsExtension/assets/5486874/864680a1-1b9c-452c-88e4-1ac28d65a4a1)


Hope that helps!

**Comment by mudesai** [comment]
Great, thank you!
