### ISSUE TITLE
Warning due to deprecated version of Node

### ISSUE THREAD

**Issue by hwt753** [huserben/PublishReleaseArtifactsExtension#36]
The extension has started to produce the following warning. Is there a plan to resolve this?

Task 'Download Release Artifact' version 1 (DownloadReleaseArtifact@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by huserben** [comment]
Hi @hwt753 

Eventually yes, but I can't tell when I'll find the time to do this.

I'll keep you posted in this issue when it's upgraded.

**Comment by huserben** [comment]
Hi @hwt753 

I updated the tasks so that the warning should be gone with the latest versions.

**Comment by hwt753** [comment]
I confirmed that the warning is no longer present. Thanks!
